# docker-compose.dev.yml
version: "3.9"

services:
  yamidtarot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - /app/node_modules        # evita que los node_modules del host rompan los del contenedor
    ports:
      - "5173:5173"              # Vite
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host --port 5173
